import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


import { Crimson_Text, Itim } from 'next/font/google';

const crimson = Crimson_Text({ 
  subsets: ['latin'], 
  weight: ['400', '700'],
  variable: '--font-crimson' 
});

const itim = Itim({ 
  subsets: ['latin'], 
  weight: ['400'],
  variable: '--font-itim' 
});


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${crimson.variable} ${itim.variable} font-sans`}>
        {children}
      </body>
    </html>
  );
}
